const Symbols = {
    cross         : '✖',
    check         : '✔',
    square        : '◻',
    filledSquare  : '◼',
    crossedSquare : '⊠',
    radioOff      : '◎',
    radioOn       : '◉',
    circle        : '◯',
    filledCircle  : '⚫',
    unchecked     : '☐',
    checked       : '☑',
    crossed       : '☒',
    heavyCheck    : '✅',
    heavyCross    : '❎',
    crossMark     : '❌',
    raisedHand    : '✋',
    raisedFist    : '✊',
    toLeft2       : '«',
    toLeft3       : '⋘',
    toRight2      : '»',
    toRight3      : '⋙',
    degree        : '°',
    rightArrow    : '►',
    downArrow     : '▼',
    magnifier1    : '🔍',
    magnifier2    : '🔎',
    pause         : '❚❚',
    resume        : '❚►',
    envelope      : '✉',
    magnifier3    : '&#x1F50D,',
    magnifier4    : '&#x1F50E,',
    clip          : '📎'
};
